/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ApproverRouteImport } from './routes/approver'
import { Route as EmployeeRouteImport } from './routes/employee'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminBookingsRouteImport } from './routes/admin.bookings'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as AdminStatisticsRouteImport } from './routes/admin.statistics'
import { Route as AdminTicketingRouteImport } from './routes/admin.ticketing'
import { Route as ApproverIndexRouteImport } from './routes/approver.index'
import { Route as ApproverPendingRouteImport } from './routes/approver.pending'
import { Route as ApproverProcessedRouteImport } from './routes/approver.processed'
import { Route as EmployeeIndexRouteImport } from './routes/employee.index'
import { Route as EmployeeBookingsRouteImport } from './routes/employee.bookings'
import { Route as EmployeeFlightsRouteImport } from './routes/employee.flights'
import { Route as EmployeeHotelsRouteImport } from './routes/employee.hotels'
import { Route as EmployeeProfileRouteImport } from './routes/employee.profile'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ApproverRoute = ApproverRouteImport.update({
  id: '/approver',
  path: '/approver',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeeRoute = EmployeeRouteImport.update({
  id: '/employee',
  path: '/employee',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBookingsRoute = AdminBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminStatisticsRoute = AdminStatisticsRouteImport.update({
  id: '/statistics',
  path: '/statistics',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTicketingRoute = AdminTicketingRouteImport.update({
  id: '/ticketing',
  path: '/ticketing',
  getParentRoute: () => AdminRoute,
} as any)
const ApproverIndexRoute = ApproverIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ApproverRoute,
} as any)
const ApproverPendingRoute = ApproverPendingRouteImport.update({
  id: '/pending',
  path: '/pending',
  getParentRoute: () => ApproverRoute,
} as any)
const ApproverProcessedRoute = ApproverProcessedRouteImport.update({
  id: '/processed',
  path: '/processed',
  getParentRoute: () => ApproverRoute,
} as any)
const EmployeeIndexRoute = EmployeeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EmployeeRoute,
} as any)
const EmployeeBookingsRoute = EmployeeBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => EmployeeRoute,
} as any)
const EmployeeFlightsRoute = EmployeeFlightsRouteImport.update({
  id: '/flights',
  path: '/flights',
  getParentRoute: () => EmployeeRoute,
} as any)
const EmployeeHotelsRoute = EmployeeHotelsRouteImport.update({
  id: '/hotels',
  path: '/hotels',
  getParentRoute: () => EmployeeRoute,
} as any)
const EmployeeProfileRoute = EmployeeProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => EmployeeRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/approver': typeof ApproverRouteWithChildren
  '/employee': typeof EmployeeRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/statistics': typeof AdminStatisticsRoute
  '/admin/ticketing': typeof AdminTicketingRoute
  '/approver/pending': typeof ApproverPendingRoute
  '/approver/processed': typeof ApproverProcessedRoute
  '/employee/bookings': typeof EmployeeBookingsRoute
  '/employee/flights': typeof EmployeeFlightsRoute
  '/employee/hotels': typeof EmployeeHotelsRoute
  '/employee/profile': typeof EmployeeProfileRoute
  '/admin/': typeof AdminIndexRoute
  '/approver/': typeof ApproverIndexRoute
  '/employee/': typeof EmployeeIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/statistics': typeof AdminStatisticsRoute
  '/admin/ticketing': typeof AdminTicketingRoute
  '/approver/pending': typeof ApproverPendingRoute
  '/approver/processed': typeof ApproverProcessedRoute
  '/employee/bookings': typeof EmployeeBookingsRoute
  '/employee/flights': typeof EmployeeFlightsRoute
  '/employee/hotels': typeof EmployeeHotelsRoute
  '/employee/profile': typeof EmployeeProfileRoute
  '/admin': typeof AdminIndexRoute
  '/approver': typeof ApproverIndexRoute
  '/employee': typeof EmployeeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/approver': typeof ApproverRouteWithChildren
  '/employee': typeof EmployeeRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/statistics': typeof AdminStatisticsRoute
  '/admin/ticketing': typeof AdminTicketingRoute
  '/approver/pending': typeof ApproverPendingRoute
  '/approver/processed': typeof ApproverProcessedRoute
  '/employee/bookings': typeof EmployeeBookingsRoute
  '/employee/flights': typeof EmployeeFlightsRoute
  '/employee/hotels': typeof EmployeeHotelsRoute
  '/employee/profile': typeof EmployeeProfileRoute
  '/admin/': typeof AdminIndexRoute
  '/approver/': typeof ApproverIndexRoute
  '/employee/': typeof EmployeeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/approver'
    | '/employee'
    | '/login'
    | '/register'
    | '/admin/bookings'
    | '/admin/dashboard'
    | '/admin/statistics'
    | '/admin/ticketing'
    | '/approver/pending'
    | '/approver/processed'
    | '/employee/bookings'
    | '/employee/flights'
    | '/employee/hotels'
    | '/employee/profile'
    | '/admin/'
    | '/approver/'
    | '/employee/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/admin/bookings'
    | '/admin/dashboard'
    | '/admin/statistics'
    | '/admin/ticketing'
    | '/approver/pending'
    | '/approver/processed'
    | '/employee/bookings'
    | '/employee/flights'
    | '/employee/hotels'
    | '/employee/profile'
    | '/admin'
    | '/approver'
    | '/employee'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/approver'
    | '/employee'
    | '/login'
    | '/register'
    | '/admin/bookings'
    | '/admin/dashboard'
    | '/admin/statistics'
    | '/admin/ticketing'
    | '/approver/pending'
    | '/approver/processed'
    | '/employee/bookings'
    | '/employee/flights'
    | '/employee/hotels'
    | '/employee/profile'
    | '/admin/'
    | '/approver/'
    | '/employee/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  ApproverRoute: typeof ApproverRouteWithChildren
  EmployeeRoute: typeof EmployeeRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/approver': {
      id: '/approver'
      path: '/approver'
      fullPath: '/approver'
      preLoaderRoute: typeof ApproverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employee': {
      id: '/employee'
      path: '/employee'
      fullPath: '/employee'
      preLoaderRoute: typeof EmployeeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/bookings': {
      id: '/admin/bookings'
      path: '/bookings'
      fullPath: '/admin/bookings'
      preLoaderRoute: typeof AdminBookingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/statistics': {
      id: '/admin/statistics'
      path: '/statistics'
      fullPath: '/admin/statistics'
      preLoaderRoute: typeof AdminStatisticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/ticketing': {
      id: '/admin/ticketing'
      path: '/ticketing'
      fullPath: '/admin/ticketing'
      preLoaderRoute: typeof AdminTicketingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/approver/': {
      id: '/approver/'
      path: '/'
      fullPath: '/approver/'
      preLoaderRoute: typeof ApproverIndexRouteImport
      parentRoute: typeof ApproverRoute
    }
    '/approver/pending': {
      id: '/approver/pending'
      path: '/pending'
      fullPath: '/approver/pending'
      preLoaderRoute: typeof ApproverPendingRouteImport
      parentRoute: typeof ApproverRoute
    }
    '/approver/processed': {
      id: '/approver/processed'
      path: '/processed'
      fullPath: '/approver/processed'
      preLoaderRoute: typeof ApproverProcessedRouteImport
      parentRoute: typeof ApproverRoute
    }
    '/employee/': {
      id: '/employee/'
      path: '/'
      fullPath: '/employee/'
      preLoaderRoute: typeof EmployeeIndexRouteImport
      parentRoute: typeof EmployeeRoute
    }
    '/employee/bookings': {
      id: '/employee/bookings'
      path: '/bookings'
      fullPath: '/employee/bookings'
      preLoaderRoute: typeof EmployeeBookingsRouteImport
      parentRoute: typeof EmployeeRoute
    }
    '/employee/flights': {
      id: '/employee/flights'
      path: '/flights'
      fullPath: '/employee/flights'
      preLoaderRoute: typeof EmployeeFlightsRouteImport
      parentRoute: typeof EmployeeRoute
    }
    '/employee/hotels': {
      id: '/employee/hotels'
      path: '/hotels'
      fullPath: '/employee/hotels'
      preLoaderRoute: typeof EmployeeHotelsRouteImport
      parentRoute: typeof EmployeeRoute
    }
    '/employee/profile': {
      id: '/employee/profile'
      path: '/profile'
      fullPath: '/employee/profile'
      preLoaderRoute: typeof EmployeeProfileRouteImport
      parentRoute: typeof EmployeeRoute
    }
  }
}

interface AdminRouteChildren {
  AdminBookingsRoute: typeof AdminBookingsRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminStatisticsRoute: typeof AdminStatisticsRoute
  AdminTicketingRoute: typeof AdminTicketingRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminBookingsRoute: AdminBookingsRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminStatisticsRoute: AdminStatisticsRoute,
  AdminTicketingRoute: AdminTicketingRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ApproverRouteChildren {
  ApproverPendingRoute: typeof ApproverPendingRoute
  ApproverProcessedRoute: typeof ApproverProcessedRoute
  ApproverIndexRoute: typeof ApproverIndexRoute
}

const ApproverRouteChildren: ApproverRouteChildren = {
  ApproverPendingRoute: ApproverPendingRoute,
  ApproverProcessedRoute: ApproverProcessedRoute,
  ApproverIndexRoute: ApproverIndexRoute,
}

const ApproverRouteWithChildren = ApproverRoute._addFileChildren(
  ApproverRouteChildren,
)

interface EmployeeRouteChildren {
  EmployeeBookingsRoute: typeof EmployeeBookingsRoute
  EmployeeFlightsRoute: typeof EmployeeFlightsRoute
  EmployeeHotelsRoute: typeof EmployeeHotelsRoute
  EmployeeProfileRoute: typeof EmployeeProfileRoute
  EmployeeIndexRoute: typeof EmployeeIndexRoute
}

const EmployeeRouteChildren: EmployeeRouteChildren = {
  EmployeeBookingsRoute: EmployeeBookingsRoute,
  EmployeeFlightsRoute: EmployeeFlightsRoute,
  EmployeeHotelsRoute: EmployeeHotelsRoute,
  EmployeeProfileRoute: EmployeeProfileRoute,
  EmployeeIndexRoute: EmployeeIndexRoute,
}

const EmployeeRouteWithChildren = EmployeeRoute._addFileChildren(
  EmployeeRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  ApproverRoute: ApproverRouteWithChildren,
  EmployeeRoute: EmployeeRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
